version: "2"

services:
  database:
    image: mysql:5.7
  app:
    build:
     context: .
     dockerfile: support/dev/Dockerfile
    working_dir: /work
    command: ./run-dev
    volumes:
      - .:/work
      - ivy-cache:/root/.ivy2/cache
      - docker-scala-sbt-cache:/root/.sbt
    depends_on: database

volumes:
  ivy-cache:
    external: true
  docker-scala-sbt-cache:
    external: true
