version: '3'

services:
  dev:
    build: support/dev
    working_dir: /work
    command: ./run-dev
    volumes:
      - .:/work
      - ivy-cache:/root/.ivy2/cache
      - docker-scala-sbt-cache:/root/.sbt

volumes:
  ivy-cache:
    external: true
  docker-scala-sbt-cache:
    external: true
